config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  resources :line_items do
    patch :save_all, on: :collection
  end

  get :kindred, to: "kindred#scope"

  root to: "invoices#index"

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  before_validation :calculate
  after_initialize :finalize

  def calculate
    self.subtotal_cents = line_items.sum(:total_cents)
    self.shipping_cents = 0
    self.tax_cents = 0
    self.total_cents = subtotal_cents + shipping_cents + tax_cents
  end


  private

  # TODO move this to kindred?
  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end

  # TODO move this to kindred?
  def finalize
    if self.attributes.has_key? "uuid"
      set_uuid
    end
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :invoice
  before_validation :calculate
  after_initialize :finalize

  validates :qty, presence: true, numericality: true
  validates :description, presence: true
  validates :price_cents, format: { :with => /\A\d+(?:\.\d{0,2})?\z/ }, numericality: {greater_than: 0, less_than: 1000000}

  def calculate
    self.total_cents = qty.to_i * price_cents.to_i
  end


  private

  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end

  def finalize
    if self.attributes.has_key? "uuid"
      set_uuid
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # TODO abstract to kindred
  after_action :setup_kindred
  helper_method :js

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
    @line_items = @invoice.line_items

    respond_to do |format|
      format.html { js }
    end
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :subtotal_cents, :shipping_cents, :tax_cents, :total_cents, :amount_due)
    end

    # TODO move this
    def setup_kindred
      view_context.content_for :kindred_script do
        js(js_class: "App.Template", function: "set_templates", args: @kindred_hash, rendered: true)
      end
    end

end

app/controllers/kindred_controller.rb
class KindredController < ApplicationController

  def scope
    model_instance = params[:class_name].constantize.find(params[:id])
    scope = model_instance.public_send(params[:relation]).to_json
    respond_to do |format|
      format.json { render json: scope }
    end
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def save_all
    response = []

    params[:line_items].values.each do |attrs|
      uuid = attrs["uuid"]
      line_item = LineItem.find_or_initialize_by(uuid: uuid)
      line_item.update_attributes(attrs)

      response << {
        line_item: line_item.attributes,
        errors: line_item.errors
      }
    end

    status = response.map { |i| i[:errors] }.any?(&:present?) ? 422 : 200

    render json: response, status: status
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:invoice_id, :description, :qty, :price_cents, :complete, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit class: "button-blue" %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<div class="top-right show-code"><a id="show-code-link" href="#">Show Code</a></div>
<div class="top-right hide-code"><a id="hide-code-link" href="#">Hide Code</a></div>
<div id="wrapper">
  <div id="main-form" class="content">
    <div class="invoice-form">
      <h1>INVOICE #<%= @invoice.id %></h1>

      <%= render 'form' %>

      <div id="line-item-buttons">
        <%= link_to 'New Line Item', "#", id: "new-line-item",
          data: { "target-uuid" => @invoice.uuid, invoice_id: @invoice.id } %>

        <%= link_to "Save All", "#", id: "line-items-save-all",
          data: { adq_uuid: "", invoice_id: @invoice.id } %>
      </div>

      <table id="line-item-table">
        <tbody <%= target @invoice %>>
          <tr>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Complete</th>
            <th>Priority</th>
            <th>Status</th>
            <th></th>
          </tr>

          <%= template(collection: @line_items, target_uuid: @invoice.uuid, model: "line_item") do %>
            <tr class="li-row">
              <td><%= k_text_field_tag(:line_item, :description) %><%= error_for(:line_item, :description) %></td>
              <td><%= k_text_field_tag(:line_item, :qty) %><%= error_for(:line_item, :qty) %></td>
              <td><%= k_text_field_tag(:line_item, :price_cents) %><%= error_for(:line_item, :price_cents) %></td>
              <td><%= k_check_box_tag(:line_item, :complete, nil, nil, class: "css-checkbox") %></td>
              <td><%= k_select_tag :line_item, "priority",
                        options_for_select(["normal", "high", "urgent"]) %>
              </td>
              <td><div data-dirty data-k-uuid=""><%= fa_icon "check-circle-o 2x", style: "color:#2ECC71" %></i></div></td>
              <td><%= link_to "Save", "#", class: "persist",
                data: { k_uuid: "{{line_item.uuid}}", invoice_id: @invoice.id } %>
              </td>
              <td><%= link_to "Delete", "#", class: "delete",
                data: { k_uuid: "{{line_item.uuid}}", id: "{{line_item.id}}" } %>
              </td>
            </tr>
          <% end %>

        </tbody>
      </table>

      <%= link_to 'Show', @invoice %> |
      <%= link_to 'Back', invoices_path %>
    </div>
  </div>
  <div class="content code">
    <h1>Model</h1>
    <pre><code class="coffeescript">
# app/assets/javascripts/models/line_item.coffee
class App.LineItem extends App.Base

  @route = "/line_items"
  @set_class_name("LineItem")

  # Override after destroy hook
  after_destroy: (data, textStatus, xhr) ->
    $("[data-error][data-k-uuid='" + @uuid + "']").parent().parent().remove()

  # Replaces status icon
  mark_dirty_or_clean: =>
    if !@id?
      $("[data-k-uuid='" + @uuid + "'][data-dirty]").html(
        "&lt;div data-dirty='' data-k-uuid='" + @uuid + "'&gt
          &lt;i class='fa fa-exclamation-triangle fa-2x' style='color:#D24D57;'&gt&lt;/i&gt
      &lt;/div&gt"
      )
    else if @dirty_from_page()
      $("[data-k-uuid='" + @uuid + "'][data-dirty]").html(
        "&lt;div data-dirty='' data-k-uuid='" + @uuid + "'&gt
          &lt;i class='fa fa-exclamation-triangle fa-2x' style='color:#F4D03F;'&gt&lt;/i&gt
      &lt;/div&gt"
      )
    else
      $("[data-k-uuid='" + @uuid + "'][data-dirty]").html(
        "&lt;div data-dirty='' data-k-uuid='" + @uuid + "'&gt
          &lt;i class='fa fa-check-circle-o fa-2x' style='color:#2ECC71;'&gt&lt;/i&gt
      &lt;/div&gt"
      )
    </code></pre>
  </div>
  <div class="content code">
    <h1>Listeners</h1>
    <pre><code class="coffeescript">
# app/assets/javascripts/listeners/invoice_listeners.coffee
class App.InvoiceListeners extends App.Listener

  # In console use `App.Listeners` to see all the listeners set on the page
  @set: ->

    # Save a single line item
    $("#line-item-table").on "click.Listeners.LineItem.save", ".persist", (evt) ->
      li = new App.LineItem({uuid: $(@).data("k-uuid")})
      li.assign_attributes_from_page()
      li.set("invoice_id", $(@).data("invoice-id"))
      li.save()
      li.mark_dirty_or_clean()

    # Removes the line item and sends delete request
    $("#line-item-table").on "click.Listeners.LineItem.delete", ".delete", (evt) ->
      li = new App.LineItem({id: $(@).data("id"), uuid: $(@).data("k-uuid")})
      li.destroy()
      $(@).parent().parent().remove()

    # Adds new line item
    $("#line-item-buttons").on "click.Listeners.LineItem.new_li", "#new-line-item", (evt) ->
      li = new App.LineItem($(@).data())
      li.append_to_page()
      li.mark_dirty_or_clean()

    # Sets the dirty or clean flag on keyup
    $("#line-item-table").on "keyup.Listeners.LineItem.dirty_input", "input[data-k-uuid]", (evt) ->
      App.LineItemsHelper.mark_li_dirty_or_clean(@)

    # Sets the dirty or clean flag on select or checkbox change
    $("#line-item-table").on "change.Listeners.LineItem.dirty_checkbox", "[data-k-uuid]", (evt) ->
      App.LineItemsHelper.mark_li_dirty_or_clean(@)

    # Submits a save all request for all the line items
    $("#line-item-buttons").on "click.Listeners.LineItem.save_all", "#line-items-save-all", (evt) ->
      App.LineItem.save_all({
        add_data_to_each: =>
          {invoice_id: $(@).data("invoice-id")}
      })
    </code></pre>
  </div>
  <div class="content code">
  <pre><code class="html">
  &lt;%= template(collection: @line_items, target: "line-item", model: "line_item") do %&gt
    &lt;tr class="li-row"&gt
      &lt;td&gt&lt;%= k_text_field_tag(:line_item, :description) %&gt&lt;/td&gt
      &lt;td&gt&lt;%= k_text_field_tag(:line_item, :qty) %&gt&lt;/td&gt
      &lt;td&gt&lt;%= k_text_field_tag(:line_item, :price_cents) %&gt&lt;/td&gt
      &lt;td&gt&lt;%= k_check_box_tag(:line_item, :complete, nil, nil, class: "css-checkbox") %&gt&lt;/td&gt
      &lt;td&gt&lt;%= k_select_tag :line_item, "priority",
                options_for_select(["normal", "high", "urgent"]) %&gt
      &lt;/td&gt
      &lt;td&gt&lt;div data-dirty data-k-uuid=""&gt&lt;%= fa_icon "check-circle-o 2x", style: "color:#2ECC71" %&gt&lt;/i&gt&lt;/div&gt&lt;/td&gt
      &lt;td&gt&lt;%= link_to "Save", "#", class: "persist",
        data: { k_uuid: "", invoice_id: @invoice.id } %&gt
      &lt;/td&gt
      &lt;td&gt&lt;%= link_to "Delete", "#", class: "delete",
        data: { k_uuid: "", id: "" } %&gt
      &lt;/td&gt
    &lt;/tr&gt
    &lt;tr&gt
      &lt;td&gt&lt;%= error_for(:line_item, :description) %&gt&lt;/td&gt
      &lt;td&gt&lt;%= error_for(:line_item, :qty) %&gt&lt;/td&gt
      &lt;td&gt&lt;%= error_for(:line_item, :price_cents) %&gt&lt;/td&gt
      &lt;td&gt&lt;/td&gt
      &lt;td&gt&lt;/td&gt
      &lt;td&gt&lt;/td&gt
    &lt;/tr&gt
  &lt;% end %&gt
  </code></pre>
  </div>
</div>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Subtotal cents</th>
      <th>Shipping cents</th>
      <th>Tax cents</th>
      <th>Total cents</th>
      <th>Amount due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.date %></td>
        <td><%= invoice.subtotal_cents %></td>
        <td><%= invoice.shipping_cents %></td>
        <td><%= invoice.tax_cents %></td>
        <td><%= invoice.total_cents %></td>
        <td><%= invoice.amount_due %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Subtotal cents:</strong>
  <%= @invoice.subtotal_cents %>
</p>

<p>
  <strong>Shipping cents:</strong>
  <%= @invoice.shipping_cents %>
</p>

<p>
  <strong>Tax cents:</strong>
  <%= @invoice.tax_cents %>
</p>

<p>
  <strong>Total cents:</strong>
  <%= @invoice.total_cents %>
</p>

<p>
  <strong>Amount due:</strong>
  <%= @invoice.amount_due %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdequateDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<!-- TODO append this stuff via js on load -->
<%= kindred_model_data %>
<%= content_for :kindred_script %>
<script type="text/javascript">
  App.BaseUrl = '<%= "#{request.protocol}#{request.host_with_port}" %>';
</script>

</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_id %><br>
    <%= f.number_field :invoice_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :qty %><br>
    <%= f.number_field :qty %>
  </div>
  <div class="field">
    <%= f.label :price_cents %><br>
    <%= f.number_field :price_cents %>
  </div>
  <div class="field">
    <%= f.label :total_cents %><br>
    <%= f.number_field :total_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Invoice</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price cents</th>
      <th>Total cents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.invoice_id %></td>
        <td><%= line_item.description %></td>
        <td><%= line_item.qty %></td>
        <td><%= line_item.price_cents %></td>
        <td><%= line_item.total_cents %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice:</strong>
  <%= @line_item.invoice_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @line_item.description %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @line_item.qty %>
</p>

<p>
  <strong>Price cents:</strong>
  <%= @line_item.price_cents %>
</p>

<p>
  <strong>Total cents:</strong>
  <%= @line_item.total_cents %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>